import { Geist, Geist_Mono } from "next/font/google";
import Script from 'next/script';
import "./globals.css";
import Navbar from '@/components/navbar'; // adjust path if needed

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden m-0 p-0`}>
        {/* reCAPTCHA script globally loaded */}
        <Script
          src="https://www.google.com/recaptcha/api.js"
          strategy="beforeInteractive"
        />
        <Navbar />
         <header className="w-full mt-8 text-center py-6">
            <h1 className="text-center text-3xl sm:text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            VoteWind!
            </h1>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
